version: 4.1.0.{build}
clone_depth: 10
install:
build: off
matrix:
  fast_finish: true

# Ruby versions under test
platform:
  - Ruby24-x64
  - Ruby23-x64

# Note that locales are mainly code page changes and are not the FULL set of localization
#  changes that happen when you install French/Germam/Japanese etc. Windows
environment:
  matrix:
  - LOCALE: en-US
  - LOCALE: ja-JP

before_test:
  # Semicolons are required below.  This renders as a single line powershell command in AppVeyor
  - ps: >-
      [string]$testLocale = [Environment]::GetEnvironmentVariable("LOCALE","Process");
      $currentLocale = (Get-WinSystemLocale).Name;
      if ($testLocale -ne '') {
        if ($testLocale -ne $currentLocale) {
          Write-Output "Setting Locale to $testLocale ...";
          Set-WinSystemLocale ($testLocale);
          Write-Output "Restarting worker in 5 seconds...";
          Start-Sleep -Seconds 5
          Restart-Computer -Force -Confirm:$false;
        } else {
          Write-Output "Locale is already set to $currentLocale";
        };
      } else {
        Write-Output "LOCALE environment variable not set";
      };

test_script:
  # The sleep is needed to allow the Appveyor tracing to start correctly after a reboot (locale change)
  # - ps: Start-Sleep -Seconds 5
  - timeout 6
  - ps: |
      chcp
      Get-WinSystemLocale
      $Env:PATH = "C:\${Env:PLATFORM}\bin;${Env:PATH}"
      $Env:LOG_SPEC_ORDER = 'true'
      Get-ChildItem Env: | % { Write-Output "$($_.Key): $($_.Value)"  }
      # list current OpenSSL install
      gem list openssl
      ruby -ropenssl -e 'puts \"OpenSSL Version - #{OpenSSL::OPENSSL_VERSION}\"; puts \"OpenSSL Library Version - #{OpenSSL::OPENSSL_LIBRARY_VERSION}\"'
      bundle install --jobs 4 --retry 2 --without development extra
      Get-Content Gemfile.lock
      ruby -v
      gem --version
      bundle --version
      bundle exec rake parallel:spec[2]
      $exitCode = $LASTEXITCODE
      Write-Output "Spec run exited with $exitCode"
      $host.SetShouldExit($exitCode)
on_failure:
  - appveyor PushArtifact .\spec_order.txt
notifications:
  - provider: Email
    to:
    - nobody@nowhere.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
